# localSettings.yaml for latexindent.pl

# Enable modification of line breaks
modifyLineBreaks: 1

# Configure text wrapping options
textWrapOptions:
  # Set the desired column limit for wrapping
  columns: 80
  # You might want to fine-tune other options here if needed,
  # but 'columns' is the primary one for line length.
  # For example, you could uncomment and adjust these:
  lookAhead: 2 # How many words to look ahead for better breaks
  tolerance: 1 # How much deviation from 'columns' is allowed if needed
  preserveBlankLines: 1 # Keep existing blank lines

# Optional: Ensure environments known to contain prose are wrapped.
# latexindent usually has good defaults, but you can add more if needed.
environments:
  mycustomproseenv:
    textWrapOptions:
      columns: 80
